apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-core-dynamisk-adapter-backend
  labels:
    fintlabs.no/org-id: novari-no

spec:
  orgId: novari-no
  envFrom:
    - configMapRef:
        name: dyna-config

  onePassword:
    itemPath: "vaults/aks-beta-vault/items/fint-core-dynamisk-adapter-beta"