apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Kustomization

resources:
  - ../../../base

namespace: novari-no

patches:
  - path: patch.yaml

configMapGenerator:
  - name: dyna-config
    files:
      - application.env

generatorOptions:
  disableNameSuffixHash: true