spring:
  application:
    name: fint-core-dyna
server:
  port: 8182

dyna:
  runtime:
    startupDomains: [ "utdanning" ]
    enableDeltaSync: false
    resetEveryNight: false
    amount-tier-policy:
    fint-properties:
      maxPageSize: 1000
      maxGeneratedResources: 10000
      heartbeatIntervalInMinutes: 3
    delta-config:
      amount-tier-policy:
        grouping: 1..3
        core: 5..5
        dependant: 5..10
        unknown: 1..3
      deltaSyncIntervalInMinutes: 10
      resources:
        - resource: ""
          component: ""
          domain: ""

  engine:
    seed: "test-seed-1"

  adapter:
    id: fint-core-dyna
    baseUrl: https://beta.felleskomponent.no
    idpUri: https://idp.felleskomponent.no/nidp/oauth/nam/token
    heartbeatIntervalInMinutes: 3
    offlineTest: True